# Generated by Django 4.0.4 on 2024-06-06 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_remove_card_date_created_alter_card_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='solved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='card',
            name='box',
            field=models.IntegerField(),
        ),
    ]
